import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
dotenv.config();

const conn = await mysql.createConnection(process.env.DATABASE_URL);

// Get first admin user
const [users] = await conn.query("SELECT id FROM users WHERE role IN ('admin','coach') LIMIT 1");
if (!users.length) { console.log('No admin user found'); process.exit(1); }
const adminId = users[0].id;

// Delete all existing training videos and replace with proper football skills videos
await conn.query("DELETE FROM training_videos");
console.log("Cleared existing training videos");

const videos = [
  // BALL CONTROL
  { title: "Ball Mastery — 10 Essential Drills", titleAr: "إتقان الكرة — 10 تمارين أساسية", description: "Master the fundamentals of ball control with these 10 essential drills used by professional academies worldwide.", descriptionAr: "أتقن أساسيات التحكم بالكرة مع هذه التمارين العشرة الأساسية المستخدمة في الأكاديميات الاحترافية حول العالم.", videoUrl: "https://www.youtube.com/watch?v=el7QvVnprOk", thumbnailUrl: "https://img.youtube.com/vi/el7QvVnprOk/hqdefault.jpg", duration: 900, category: "ball_control", difficulty: "beginner", ageGroup: "all", tags: '["ball_control","mastery","beginner"]', views: 2400 },
  { title: "First Touch Mastery — All Surfaces", titleAr: "إتقان اللمسة الأولى — جميع الأسطح", description: "Develop a reliable first touch with inside, outside, sole, and chest control in all directions.", descriptionAr: "طور لمسة أولى موثوقة بالداخل والخارج والنعل والصدر في جميع الاتجاهات.", videoUrl: "https://www.youtube.com/watch?v=vFvMFNKmXMo", thumbnailUrl: "https://img.youtube.com/vi/vFvMFNKmXMo/hqdefault.jpg", duration: 840, category: "ball_control", difficulty: "beginner", ageGroup: "U10", tags: '["first_touch","control","receiving"]', views: 1670 },
  { title: "Weak Foot Training Program", titleAr: "برنامج تدريب القدم الضعيفة", description: "A structured 4-week program to develop your weaker foot and become truly two-footed.", descriptionAr: "برنامج منظم لمدة 4 أسابيع لتطوير قدمك الضعيفة.", videoUrl: "https://www.youtube.com/watch?v=el7QvVnprOk", thumbnailUrl: "https://img.youtube.com/vi/el7QvVnprOk/hqdefault.jpg", duration: 1080, category: "ball_control", difficulty: "intermediate", ageGroup: "all", tags: '["weak_foot","two_footed","development"]', views: 980 },
  // PASSING
  { title: "Short & Long Passing Fundamentals", titleAr: "أساسيات التمرير القصير والطويل", description: "Master both short and long passing with correct technique, weight, and timing to unlock defenses.", descriptionAr: "أتقن التمرير القصير والطويل بالتقنية الصحيحة والوزن والتوقيت.", videoUrl: "https://www.youtube.com/watch?v=-V88Iy1X-is", thumbnailUrl: "https://img.youtube.com/vi/-V88Iy1X-is/hqdefault.jpg", duration: 900, category: "passing", difficulty: "beginner", ageGroup: "all", tags: '["passing","technique","fundamentals"]', views: 1890 },
  { title: "Rondo Possession Drill — 4v1 & 5v2", titleAr: "تمرين الروندو للاستحواذ", description: "Classic rondo possession drills to improve quick passing, movement, and decision making under pressure.", descriptionAr: "تمارين الروندو الكلاسيكية لتحسين التمرير السريع والحركة واتخاذ القرار تحت الضغط.", videoUrl: "https://www.youtube.com/watch?v=M5JxnEJqkMo", thumbnailUrl: "https://img.youtube.com/vi/M5JxnEJqkMo/hqdefault.jpg", duration: 600, category: "passing", difficulty: "intermediate", ageGroup: "all", tags: '["rondo","possession","passing","pressure"]', views: 1430 },
  { title: "One-Two Passing Combinations", titleAr: "توليفات التمرير واحد-اثنين", description: "Practice wall passes and one-two combinations to break defensive lines.", descriptionAr: "تدرب على التمريرات الجدارية وتوليفات واحد-اثنين لاختراق الخطوط الدفاعية.", videoUrl: "https://www.youtube.com/watch?v=9aHmBjWdRIk", thumbnailUrl: "https://img.youtube.com/vi/9aHmBjWdRIk/hqdefault.jpg", duration: 720, category: "passing", difficulty: "intermediate", ageGroup: "U12", tags: '["passing","combination","one_two"]', views: 1120 },
  // SHOOTING
  { title: "Shooting Power & Accuracy Training", titleAr: "تدريب قوة ودقة التسديد", description: "Develop powerful and accurate shooting technique with proper body mechanics, stance, and follow-through.", descriptionAr: "طور تقنية التسديد القوية والدقيقة مع ميكانيكا الجسم الصحيحة.", videoUrl: "https://www.youtube.com/watch?v=bHGW2apqfEE", thumbnailUrl: "https://img.youtube.com/vi/bHGW2apqfEE/hqdefault.jpg", duration: 1200, category: "shooting", difficulty: "intermediate", ageGroup: "U12", tags: '["shooting","power","accuracy","technique"]', views: 2100 },
  { title: "Free Kick Technique — Power & Placement", titleAr: "تقنية الركلة الحرة — القوة والتوجيه", description: "Master free kick technique including run-up, contact point, and how to bend the ball over the wall.", descriptionAr: "أتقن تقنية الركلة الحرة بما فيها الاقتراب ونقطة التلامس وكيفية تحريف الكرة فوق الحائط.", videoUrl: "https://www.youtube.com/watch?v=Yl5BNguO7HY", thumbnailUrl: "https://img.youtube.com/vi/Yl5BNguO7HY/hqdefault.jpg", duration: 900, category: "shooting", difficulty: "advanced", ageGroup: "U14", tags: '["free_kick","shooting","set_piece","bend"]', views: 1760 },
  { title: "Crossing & Finishing Combination", titleAr: "مجموعة العرضيات والإنهاء", description: "Practice crossing from wide positions and finishing with headers and volleys in the penalty area.", descriptionAr: "تدرب على العرضيات من المواقع الواسعة والإنهاء بالكرة الرأسية والفولي.", videoUrl: "https://www.youtube.com/watch?v=Yl5BNguO7HY", thumbnailUrl: "https://img.youtube.com/vi/Yl5BNguO7HY/hqdefault.jpg", duration: 1080, category: "shooting", difficulty: "intermediate", ageGroup: "U14", tags: '["crossing","finishing","heading","volley"]', views: 1340 },
  // DRIBBLING
  { title: "Advanced Dribbling Techniques", titleAr: "تقنيات المراوغة المتقدمة", description: "Learn advanced dribbling moves including the Cruyff turn, elastico, and step-over combinations.", descriptionAr: "تعلم حركات المراوغة المتقدمة بما فيها دوران كرويف والإيلاستيكو والتغطية.", videoUrl: "https://www.youtube.com/watch?v=Hs4ByFF_AE0", thumbnailUrl: "https://img.youtube.com/vi/Hs4ByFF_AE0/hqdefault.jpg", duration: 1200, category: "dribbling", difficulty: "advanced", ageGroup: "U14", tags: '["advanced","dribbling","cruyff","elastico"]', views: 1980 },
  { title: "Cone Dribbling — Zig Zag & Slalom", titleAr: "المراوغة بالمخاريط — زيغ زاغ وسلالوم", description: "Improve close control and dribbling speed with cone zig-zag and slalom exercises.", descriptionAr: "حسّن التحكم القريب وسرعة المراوغة مع تمارين الزيغ زاغ والسلالوم بالمخاريط.", videoUrl: "https://www.youtube.com/watch?v=3Rl0BFKX-Jg", thumbnailUrl: "https://img.youtube.com/vi/3Rl0BFKX-Jg/hqdefault.jpg", duration: 540, category: "dribbling", difficulty: "beginner", ageGroup: "U10", tags: '["dribbling","cones","zig_zag","close_control"]', views: 1560 },
  { title: "1v1 Attacking Moves & Feints", titleAr: "حركات هجومية وخدع 1 ضد 1", description: "Learn the best 1v1 moves and feints to beat defenders in tight spaces and create goal chances.", descriptionAr: "تعلم أفضل حركات وخدع 1 ضد 1 للتغلب على المدافعين في الأماكن الضيقة.", videoUrl: "https://www.youtube.com/watch?v=jwIHc9rz7yo", thumbnailUrl: "https://img.youtube.com/vi/jwIHc9rz7yo/hqdefault.jpg", duration: 1200, category: "dribbling", difficulty: "intermediate", ageGroup: "U12", tags: '["dribbling","1v1","feints","moves"]', views: 1820 },
  // SPEED & AGILITY
  { title: "Speed & Agility Ladder Drills", titleAr: "تمارين السرعة والرشاقة بالسلم", description: "Improve your speed, agility, and coordination with these ladder and cone drills used by elite players.", descriptionAr: "حسّن سرعتك ورشاقتك وتنسيقك مع تمارين السلم والمخاريط.", videoUrl: "https://www.youtube.com/watch?v=jwIHc9rz7yo", thumbnailUrl: "https://img.youtube.com/vi/jwIHc9rz7yo/hqdefault.jpg", duration: 900, category: "speed_agility", difficulty: "intermediate", ageGroup: "all", tags: '["speed","agility","fitness","ladder"]', views: 2230 },
  { title: "Explosive Sprint Training for Footballers", titleAr: "تدريب العدو الانفجاري للاعبي كرة القدم", description: "Develop explosive acceleration and top speed with these football-specific sprint drills.", descriptionAr: "طور التسارع الانفجاري والسرعة القصوى مع تمارين العدو الخاصة بكرة القدم.", videoUrl: "https://www.youtube.com/watch?v=NyBmRZgMTas", thumbnailUrl: "https://img.youtube.com/vi/NyBmRZgMTas/hqdefault.jpg", duration: 780, category: "speed_agility", difficulty: "intermediate", ageGroup: "U14", tags: '["sprint","speed","explosive","acceleration"]', views: 1450 },
  // POSITIONING
  { title: "Defensive Positioning & Tackling", titleAr: "التمركز الدفاعي والتدخل", description: "Master defensive positioning, jockeying, and timing your tackles to win the ball cleanly.", descriptionAr: "أتقن التمركز الدفاعي والمراوغة الدفاعية وتوقيت التدخلات.", videoUrl: "https://www.youtube.com/watch?v=LR9ifmPXGhI", thumbnailUrl: "https://img.youtube.com/vi/LR9ifmPXGhI/hqdefault.jpg", duration: 1200, category: "positioning", difficulty: "intermediate", ageGroup: "U14", tags: '["defending","positioning","tackling"]', views: 1340 },
  { title: "Attacking Positioning — Creating Space", titleAr: "التمركز الهجومي — خلق المساحات", description: "Understand attacking positioning, movement patterns, and creating space in the final third.", descriptionAr: "افهم التمركز الهجومي وأنماط الحركة وخلق المساحات في الثلث الأخير.", videoUrl: "https://www.youtube.com/watch?v=uBlSzlbvsvo", thumbnailUrl: "https://img.youtube.com/vi/uBlSzlbvsvo/hqdefault.jpg", duration: 1500, category: "positioning", difficulty: "advanced", ageGroup: "U16", tags: '["positioning","attacking","space","movement"]', views: 1120 },
  // HEADING
  { title: "Heading Technique & Timing", titleAr: "تقنية وتوقيت الكرة الرأسية", description: "Learn proper heading technique, timing your jump, and directing headers on goal or for clearances.", descriptionAr: "تعلم تقنية الكرة الرأسية الصحيحة وتوقيت القفز وتوجيه الضربات الرأسية.", videoUrl: "https://www.youtube.com/watch?v=bHGW2apqfEE", thumbnailUrl: "https://img.youtube.com/vi/bHGW2apqfEE/hqdefault.jpg", duration: 720, category: "heading", difficulty: "intermediate", ageGroup: "U12", tags: '["heading","aerial","timing","technique"]', views: 980 },
  // FITNESS
  { title: "Fitness & Endurance Training for Football", titleAr: "تدريب اللياقة والتحمل لكرة القدم", description: "Build your aerobic base and football-specific endurance with these proven training protocols.", descriptionAr: "ابنِ قاعدتك الهوائية وتحملك الخاص بكرة القدم.", videoUrl: "https://www.youtube.com/watch?v=jwIHc9rz7yo", thumbnailUrl: "https://img.youtube.com/vi/jwIHc9rz7yo/hqdefault.jpg", duration: 900, category: "fitness", difficulty: "beginner", ageGroup: "all", tags: '["fitness","endurance","conditioning","aerobic"]', views: 1670 },
  { title: "Strength & Conditioning for Footballers", titleAr: "القوة والتكييف للاعبي كرة القدم", description: "Football-specific strength and conditioning exercises to improve physical duels, jumping, and athleticism.", descriptionAr: "تمارين القوة والتكييف الخاصة بكرة القدم لتحسين المبارزات الجسدية.", videoUrl: "https://www.youtube.com/watch?v=NyBmRZgMTas", thumbnailUrl: "https://img.youtube.com/vi/NyBmRZgMTas/hqdefault.jpg", duration: 1320, category: "fitness", difficulty: "intermediate", ageGroup: "U16", tags: '["strength","conditioning","physical","athleticism"]', views: 1230 },
  // TACTICAL
  { title: "High Pressing — Tactical Masterclass", titleAr: "الضغط العالي — درس تكتيكي", description: "Learn how to implement a high press system with pressing triggers, compactness, and recovery runs.", descriptionAr: "تعلم كيفية تطبيق نظام الضغط العالي مع محفزات الضغط والتماسك.", videoUrl: "https://www.youtube.com/watch?v=uBlSzlbvsvo", thumbnailUrl: "https://img.youtube.com/vi/uBlSzlbvsvo/hqdefault.jpg", duration: 1500, category: "tactical", difficulty: "advanced", ageGroup: "U16", tags: '["pressing","tactical","advanced","gegenpressing"]', views: 1434 },
  { title: "4-3-3 Formation Attacking Movements", titleAr: "تشكيل 4-3-3 الحركات الهجومية", description: "Understand the attacking movements, rotations, and overloads in a 4-3-3 formation.", descriptionAr: "افهم الحركات الهجومية والتناوبات والتحميلات في تشكيل 4-3-3.", videoUrl: "https://www.youtube.com/watch?v=9aHmBjWdRIk", thumbnailUrl: "https://img.youtube.com/vi/9aHmBjWdRIk/hqdefault.jpg", duration: 1560, category: "tactical", difficulty: "advanced", ageGroup: "U16", tags: '["tactical","formation","attacking","433"]', views: 1143 },
  { title: "Tiki-Taka Passing Combinations", titleAr: "توليفات التمرير بأسلوب تيكي-تاكا", description: "Master the tiki-taka style with quick one-touch passing combinations in tight spaces.", descriptionAr: "أتقن أسلوب تيكي-تاكا مع توليفات التمرير بلمسة واحدة في الأماكن الضيقة.", videoUrl: "https://www.youtube.com/watch?v=9aHmBjWdRIk", thumbnailUrl: "https://img.youtube.com/vi/9aHmBjWdRIk/hqdefault.jpg", duration: 1380, category: "tactical", difficulty: "advanced", ageGroup: "all", tags: '["passing","tiki_taka","tactical"]', views: 646 },
  // GOALKEEPING
  { title: "Goalkeeper Footwork & Distribution", titleAr: "حركة قدم الحارس وتوزيع الكرة", description: "Essential goalkeeper footwork patterns and distribution techniques for modern goalkeepers.", descriptionAr: "أنماط حركة القدم الأساسية لحارس المرمى وتقنيات التوزيع للحراس المعاصرين.", videoUrl: "https://www.youtube.com/watch?v=TviVDUBTQVU", thumbnailUrl: "https://img.youtube.com/vi/TviVDUBTQVU/hqdefault.jpg", duration: 1800, category: "goalkeeping", difficulty: "intermediate", ageGroup: "all", tags: '["goalkeeping","footwork","distribution"]', views: 1200 },
  { title: "Goalkeeper Diving & Shot Stopping", titleAr: "الغطس وإيقاف التسديدات لحارس المرمى", description: "Learn proper diving technique, positioning, and reflexes to stop shots from all angles.", descriptionAr: "تعلم تقنية الغطس الصحيحة والتمركز وردود الفعل لإيقاف التسديدات من جميع الزوايا.", videoUrl: "https://www.youtube.com/watch?v=TviVDUBTQVU", thumbnailUrl: "https://img.youtube.com/vi/TviVDUBTQVU/hqdefault.jpg", duration: 1440, category: "goalkeeping", difficulty: "intermediate", ageGroup: "U12", tags: '["goalkeeping","diving","shot_stopping","reflexes"]', views: 890 },
];

let inserted = 0;
for (const v of videos) {
  try {
    await conn.query(
      `INSERT INTO training_videos (title, titleAr, description, descriptionAr, videoUrl, thumbnailUrl, duration, category, difficulty, ageGroup, tags, uploadedBy, isPublished, viewCount) 
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?)`,
      [v.title, v.titleAr, v.description, v.descriptionAr, v.videoUrl, v.thumbnailUrl, v.duration, v.category, v.difficulty, v.ageGroup, v.tags, adminId, v.views]
    );
    inserted++;
  } catch(e) { console.error('Error inserting:', v.title, e.message); }
}
console.log(`Inserted ${inserted} training videos with correct football categories`);
await conn.end();
