import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
dotenv.config();

const conn = await mysql.createConnection(process.env.DATABASE_URL);

// Get first admin user
const [users] = await conn.query("SELECT id FROM users WHERE role IN ('admin','coach') LIMIT 1");
if (!users.length) { console.log('No admin user found'); process.exit(1); }
const adminId = users[0].id;
console.log('Using admin user ID:', adminId);

// Check existing count
const [cnt] = await conn.query("SELECT COUNT(*) as c FROM training_videos WHERE isPublished=1");
console.log('Existing published videos:', cnt[0].c);

if (cnt[0].c >= 20) { console.log('Already seeded'); process.exit(0); }

const videos = [
  { title: "Ball Mastery — 10 Essential Drills", titleAr: "إتقان الكرة — 10 تمارين أساسية", description: "Master the fundamentals of ball control with these 10 essential drills used by professional academies worldwide.", descriptionAr: "أتقن أساسيات التحكم بالكرة مع هذه التمارين العشرة الأساسية المستخدمة في الأكاديميات الاحترافية حول العالم.", videoUrl: "https://www.youtube.com/watch?v=el7QvVnprOk", thumbnailUrl: "https://img.youtube.com/vi/el7QvVnprOk/hqdefault.jpg", duration: 900, category: "ball_control", difficulty: "beginner", ageGroup: "all", tags: '["beginner","ball","control","mastery"]' },
  { title: "Advanced Dribbling Techniques", titleAr: "تقنيات المراوغة المتقدمة", description: "Learn advanced dribbling moves including the Cruyff turn, elastico, and step-over combinations used by pros.", descriptionAr: "تعلم حركات المراوغة المتقدمة بما فيها دوران كرويف والإيلاستيكو والتغطية المستخدمة من قبل المحترفين.", videoUrl: "https://www.youtube.com/watch?v=Hs4ByFF_AE0", thumbnailUrl: "https://img.youtube.com/vi/Hs4ByFF_AE0/hqdefault.jpg", duration: 1200, category: "dribbling", difficulty: "advanced", ageGroup: "U14", tags: '["advanced","dribbling","moves","cruyff"]' },
  { title: "Shooting Power & Accuracy Training", titleAr: "تدريب قوة ودقة التسديد", description: "Develop powerful and accurate shooting technique with proper body mechanics, stance, and follow-through.", descriptionAr: "طور تقنية التسديد القوية والدقيقة مع ميكانيكا الجسم الصحيحة والوقفة والمتابعة.", videoUrl: "https://www.youtube.com/watch?v=bHGW2apqfEE", thumbnailUrl: "https://img.youtube.com/vi/bHGW2apqfEE/hqdefault.jpg", duration: 1200, category: "shooting", difficulty: "intermediate", ageGroup: "U12", tags: '["shooting","power","accuracy","technique"]' },
  { title: "Short & Long Passing Fundamentals", titleAr: "أساسيات التمرير القصير والطويل", description: "Master both short and long passing with correct technique, weight, and timing to unlock defenses.", descriptionAr: "أتقن التمرير القصير والطويل بالتقنية الصحيحة والوزن والتوقيت لفتح الدفاعات.", videoUrl: "https://www.youtube.com/watch?v=-V88Iy1X-is", thumbnailUrl: "https://img.youtube.com/vi/-V88Iy1X-is/hqdefault.jpg", duration: 900, category: "passing", difficulty: "beginner", ageGroup: "all", tags: '["passing","technique","fundamentals","short","long"]' },
  { title: "Speed & Agility Ladder Drills", titleAr: "تمارين السرعة والرشاقة بالسلم", description: "Improve your speed, agility, and coordination with these ladder and cone drills used by elite players.", descriptionAr: "حسّن سرعتك ورشاقتك وتنسيقك مع تمارين السلم والمخاريط المستخدمة من قبل اللاعبين النخبة.", videoUrl: "https://www.youtube.com/watch?v=jwIHc9rz7yo", thumbnailUrl: "https://img.youtube.com/vi/jwIHc9rz7yo/hqdefault.jpg", duration: 900, category: "speed_agility", difficulty: "intermediate", ageGroup: "all", tags: '["speed","agility","fitness","ladder","coordination"]' },
  { title: "Tactical Positioning — Attacking Phase", titleAr: "التمركز التكتيكي — مرحلة الهجوم", description: "Understand attacking positioning, movement patterns, and creating space in the final third.", descriptionAr: "افهم التمركز الهجومي وأنماط الحركة وخلق المساحات في الثلث الأخير.", videoUrl: "https://www.youtube.com/watch?v=uBlSzlbvsvo", thumbnailUrl: "https://img.youtube.com/vi/uBlSzlbvsvo/hqdefault.jpg", duration: 1500, category: "tactical", difficulty: "advanced", ageGroup: "U16", tags: '["tactical","positioning","attacking","space"]' },
  { title: "Heading Technique & Timing", titleAr: "تقنية وتوقيت الكرة الرأسية", description: "Learn proper heading technique, timing your jump, and directing headers on goal or for clearances.", descriptionAr: "تعلم تقنية الكرة الرأسية الصحيحة وتوقيت القفز وتوجيه الضربات الرأسية نحو المرمى أو للتطهير.", videoUrl: "https://www.youtube.com/watch?v=bHGW2apqfEE", thumbnailUrl: "https://img.youtube.com/vi/bHGW2apqfEE/hqdefault.jpg", duration: 720, category: "heading", difficulty: "intermediate", ageGroup: "U12", tags: '["heading","aerial","timing","technique"]' },
  { title: "Goalkeeper Footwork & Distribution", titleAr: "حركة قدم الحارس وتوزيع الكرة", description: "Essential goalkeeper footwork patterns and distribution techniques for modern goalkeepers.", descriptionAr: "أنماط حركة القدم الأساسية لحارس المرمى وتقنيات التوزيع للحراس المعاصرين.", videoUrl: "https://www.youtube.com/watch?v=TviVDUBTQVU", thumbnailUrl: "https://img.youtube.com/vi/TviVDUBTQVU/hqdefault.jpg", duration: 1800, category: "goalkeeping", difficulty: "intermediate", ageGroup: "all", tags: '["goalkeeping","footwork","distribution","technique"]' },
  { title: "Fitness & Endurance Training for Football", titleAr: "تدريب اللياقة والتحمل لكرة القدم", description: "Build your aerobic base and football-specific endurance with these proven training protocols.", descriptionAr: "ابنِ قاعدتك الهوائية وتحملك الخاص بكرة القدم مع بروتوكولات التدريب المثبتة هذه.", videoUrl: "https://www.youtube.com/watch?v=jwIHc9rz7yo", thumbnailUrl: "https://img.youtube.com/vi/jwIHc9rz7yo/hqdefault.jpg", duration: 900, category: "fitness", difficulty: "beginner", ageGroup: "all", tags: '["fitness","endurance","conditioning","aerobic"]' },
  { title: "Weak Foot Training Program", titleAr: "برنامج تدريب القدم الضعيفة", description: "A structured 4-week program to develop your weaker foot and become truly two-footed.", descriptionAr: "برنامج منظم لمدة 4 أسابيع لتطوير قدمك الضعيفة وتصبح قادراً على اللعب بكلتا القدمين.", videoUrl: "https://www.youtube.com/watch?v=el7QvVnprOk", thumbnailUrl: "https://img.youtube.com/vi/el7QvVnprOk/hqdefault.jpg", duration: 1080, category: "ball_control", difficulty: "intermediate", ageGroup: "all", tags: '["weak_foot","two_footed","development","training"]' },
  { title: "Defensive Positioning & Tackling", titleAr: "التمركز الدفاعي والتدخل", description: "Master defensive positioning, jockeying, and timing your tackles to win the ball cleanly.", descriptionAr: "أتقن التمركز الدفاعي والمراوغة الدفاعية وتوقيت التدخلات لاستعادة الكرة بنظافة.", videoUrl: "https://www.youtube.com/watch?v=LR9ifmPXGhI", thumbnailUrl: "https://img.youtube.com/vi/LR9ifmPXGhI/hqdefault.jpg", duration: 1200, category: "positioning", difficulty: "intermediate", ageGroup: "U14", tags: '["defending","positioning","tackling","jockeying"]' },
  { title: "First Touch Mastery", titleAr: "إتقان اللمسة الأولى", description: "Develop a reliable first touch in all directions and under pressure with these progressive drills.", descriptionAr: "طور لمسة أولى موثوقة في جميع الاتجاهات وتحت الضغط مع هذه التمارين التدريجية.", videoUrl: "https://www.youtube.com/watch?v=el7QvVnprOk", thumbnailUrl: "https://img.youtube.com/vi/el7QvVnprOk/hqdefault.jpg", duration: 900, category: "ball_control", difficulty: "beginner", ageGroup: "U10", tags: '["first_touch","control","receiving","beginner"]' },
  { title: "High Pressing — Tactical Masterclass", titleAr: "الضغط العالي — درس تكتيكي", description: "Learn how to implement a high press system with pressing triggers, compactness, and recovery runs.", descriptionAr: "تعلم كيفية تطبيق نظام الضغط العالي مع محفزات الضغط والتماسك وجري الاسترداد.", videoUrl: "https://www.youtube.com/watch?v=uBlSzlbvsvo", thumbnailUrl: "https://img.youtube.com/vi/uBlSzlbvsvo/hqdefault.jpg", duration: 1500, category: "tactical", difficulty: "advanced", ageGroup: "U16", tags: '["pressing","tactical","advanced","gegenpressing"]' },
  { title: "1v1 Attacking Moves & Feints", titleAr: "حركات هجومية وخدع 1 ضد 1", description: "Learn the best 1v1 moves and feints to beat defenders in tight spaces and create goal chances.", descriptionAr: "تعلم أفضل حركات وخدع 1 ضد 1 للتغلب على المدافعين في الأماكن الضيقة وخلق فرص تهديفية.", videoUrl: "https://www.youtube.com/watch?v=jwIHc9rz7yo", thumbnailUrl: "https://img.youtube.com/vi/jwIHc9rz7yo/hqdefault.jpg", duration: 1200, category: "dribbling", difficulty: "intermediate", ageGroup: "U12", tags: '["dribbling","1v1","feints","moves"]' },
  { title: "Rondo Possession Drill — 4v1 & 5v2", titleAr: "تمرين الروندو للاستحواذ — 4 ضد 1 و 5 ضد 2", description: "Classic rondo possession drills to improve quick passing, movement, and decision making under pressure.", descriptionAr: "تمارين الروندو الكلاسيكية للاستحواذ لتحسين التمرير السريع والحركة واتخاذ القرار تحت الضغط.", videoUrl: "https://www.youtube.com/watch?v=M5JxnEJqkMo", thumbnailUrl: "https://img.youtube.com/vi/M5JxnEJqkMo/hqdefault.jpg", duration: 600, category: "passing", difficulty: "intermediate", ageGroup: "all", tags: '["rondo","possession","passing","pressure","decision"]' },
  { title: "Free Kick Technique — Power & Placement", titleAr: "تقنية الركلة الحرة — القوة والتوجيه", description: "Master free kick technique including run-up, contact point, and how to bend the ball over the wall.", descriptionAr: "أتقن تقنية الركلة الحرة بما فيها الاقتراب ونقطة التلامس وكيفية تحريف الكرة فوق الحائط.", videoUrl: "https://www.youtube.com/watch?v=Yl5BNguO7HY", thumbnailUrl: "https://img.youtube.com/vi/Yl5BNguO7HY/hqdefault.jpg", duration: 900, category: "shooting", difficulty: "advanced", ageGroup: "U14", tags: '["free_kick","shooting","technique","set_piece","bend"]' },
  { title: "Cone Dribbling — Zig Zag & Slalom", titleAr: "المراوغة بالمخاريط — زيغ زاغ وسلالوم", description: "Improve close control and dribbling speed with cone zig-zag and slalom exercises for all ages.", descriptionAr: "حسّن التحكم القريب وسرعة المراوغة مع تمارين الزيغ زاغ والسلالوم بالمخاريط لجميع الأعمار.", videoUrl: "https://www.youtube.com/watch?v=3Rl0BFKX-Jg", thumbnailUrl: "https://img.youtube.com/vi/3Rl0BFKX-Jg/hqdefault.jpg", duration: 540, category: "dribbling", difficulty: "beginner", ageGroup: "U10", tags: '["dribbling","cones","zig_zag","close_control","youth"]' },
  { title: "Crossing & Finishing Combination", titleAr: "مجموعة العرضيات والإنهاء", description: "Practice crossing from wide positions and finishing with headers and volleys in the penalty area.", descriptionAr: "تدرب على العرضيات من المواقع الواسعة والإنهاء بالكرة الرأسية والفولي في منطقة الجزاء.", videoUrl: "https://www.youtube.com/watch?v=Yl5BNguO7HY", thumbnailUrl: "https://img.youtube.com/vi/Yl5BNguO7HY/hqdefault.jpg", duration: 1080, category: "shooting", difficulty: "intermediate", ageGroup: "U14", tags: '["crossing","finishing","heading","volley","combination"]' },
  { title: "Strength & Conditioning for Footballers", titleAr: "القوة والتكييف للاعبي كرة القدم", description: "Football-specific strength and conditioning exercises to improve physical duels, jumping, and athleticism.", descriptionAr: "تمارين القوة والتكييف الخاصة بكرة القدم لتحسين المبارزات الجسدية والقفز والرياضية.", videoUrl: "https://www.youtube.com/watch?v=NyBmRZgMTas", thumbnailUrl: "https://img.youtube.com/vi/NyBmRZgMTas/hqdefault.jpg", duration: 1320, category: "fitness", difficulty: "intermediate", ageGroup: "U16", tags: '["strength","conditioning","fitness","physical","athleticism"]' },
  { title: "Positional Play — Third Man Combinations", titleAr: "اللعب الموضعي — توليفات الرجل الثالث", description: "Learn third-man combination play to create space and break defensive lines with quick passing sequences.", descriptionAr: "تعلم لعب توليفات الرجل الثالث لخلق المساحات واختراق الخطوط الدفاعية بتسلسلات التمرير السريع.", videoUrl: "https://www.youtube.com/watch?v=9aHmBjWdRIk", thumbnailUrl: "https://img.youtube.com/vi/9aHmBjWdRIk/hqdefault.jpg", duration: 1200, category: "tactical", difficulty: "advanced", ageGroup: "U16", tags: '["tactical","positional_play","third_man","combinations"]' },
];

let inserted = 0;
for (const v of videos) {
  try {
    await conn.query(
      `INSERT INTO training_videos (title, titleAr, description, descriptionAr, videoUrl, thumbnailUrl, duration, category, difficulty, ageGroup, tags, uploadedBy, isPublished, viewCount) 
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?)`,
      [v.title, v.titleAr, v.description, v.descriptionAr, v.videoUrl, v.thumbnailUrl, v.duration, v.category, v.difficulty, v.ageGroup, v.tags, adminId, Math.floor(Math.random() * 3000)]
    );
    inserted++;
  } catch(e) { console.error('Error inserting:', v.title, e.message); }
}
console.log(`Inserted ${inserted} training videos`);
await conn.end();
