import { useParams } from "wouter";
import { trpc } from "@/lib/trpc";
import { MarkdownContent } from "@/components/MarkdownContent";
import { Loader2, Brain, AlertCircle, Calendar, User, Film } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export default function SharedAnalysisReport() {
  const params = useParams<{ token: string }>();
  const token = params.token || "";

  const { data: report, isLoading, error } = trpc.aiVideoAnalysis.getSharedReport.useQuery(
    { token },
    { enabled: !!token }
  );

  if (isLoading) {
    return (
      <div className="min-h-[60vh] flex items-center justify-center">
        <div className="flex flex-col items-center gap-3 text-muted-foreground">
          <Loader2 className="h-8 w-8 animate-spin" />
          <p className="text-sm">Loading shared report…</p>
        </div>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="min-h-[60vh] flex items-center justify-center">
        <div className="flex flex-col items-center gap-3 text-center px-4">
          <AlertCircle className="h-12 w-12 text-destructive" />
          <h2 className="text-lg font-semibold">Report Not Found</h2>
          <p className="text-sm text-muted-foreground max-w-sm">
            This shared report link is invalid or has been removed. Please ask the owner to share it again.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div >
      {/* Header */}
      <div className="border-b bg-card">
        <div className="max-w-4xl mx-auto px-4 py-4 flex items-center gap-3">
          <div className="h-9 w-9 rounded-lg bg-primary/10 flex items-center justify-center">
            <Brain className="h-5 w-5 text-primary" />
          </div>
          <div>
            <p className="text-xs text-muted-foreground font-medium uppercase tracking-wide">AI Video Analysis Report</p>
            <h1 className="text-base font-semibold leading-tight">{report.title}</h1>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 py-6 space-y-5">
        {/* Meta */}
        <Card>
          <CardContent className="p-4">
            <div className="flex flex-wrap gap-3 text-sm text-muted-foreground">
              {report.player_name && (
                <div className="flex items-center gap-1.5">
                  <User className="h-4 w-4" />
                  <span>{report.player_name}</span>
                </div>
              )}
              {report.frames_analyzed > 0 && (
                <div className="flex items-center gap-1.5">
                  <Film className="h-4 w-4" />
                  <span>{report.frames_analyzed} frames analyzed</span>
                </div>
              )}
              <div className="flex items-center gap-1.5">
                <Calendar className="h-4 w-4" />
                <span>{new Date(report.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</span>
              </div>
              <Badge variant="secondary" className="capitalize">{report.analysis_type}</Badge>
            </div>
          </CardContent>
        </Card>

        {/* Report Body */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-base flex items-center gap-2">
              <Brain className="h-4 w-4 text-primary" />
              Analysis Report
            </CardTitle>
          </CardHeader>
          <CardContent>
            <MarkdownContent content={report.report_content} />
          </CardContent>
        </Card>

        {/* Footer */}
        <p className="text-center text-xs text-muted-foreground pb-6">
          Generated by Future Stars Football Academy · AI Video Analysis
        </p>
      </div>
    </div>
  );
}
